### PR TITLE
Cov matrix

### PR DESCRIPTION
**Pull request by ajafarihub**
The covariance-enhanced version of VB is implemented together with the updated formulation and few test-cases.

### CODE REVIEW

**Comment by ajafarihub** [comment]
All the checks are not fulfilled go to the same error:
AttributeError: 'multivariate_normal_frozen' object has no attribute 'cov'
However, the scipy documentation asserts that such attribute (cov) is valid:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.multivariate_normal.html
So I am not sure why the checks are not passed.

**Comment by joergfunger** [comment]
You are not using scipy objects, but mvn is defined in bayem [here](https://github.com/BAMresearch/bayem/blob/covMatrix/bayem/distributions.py). Did you run the tests on your machine before pushing?

**Comment by ajafarihub** [comment]
Yes I did check it on my machine and all the tests are passed. As far as I see, the MVN object has the 'dist' method in which scipy objects are used. Though, I cannot see the details of the error here anymore (no idea why). I also wonder why/how the changes that I've made into this branch should be related to the MVN class/tests, since I made no change to them.

**Comment by joergfunger** [comment]
I don't think this is related to your changes, in particular since python3.7 is working, only 3.8-3.10 are not working. Did you check these with your conda environment (changing python to 3.10)?

**Comment by ajafarihub** [comment]
No I did not test with various python versions. However, my conda environment's python version is **3.8.2** and it just normally pass all the tests !

**Comment by ajafarihub** [comment]
@joergfunger , the issue was something related to scipy-v.1.10:
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1891357.html
It is now resolved by avoiding to use version 1.10 of scipy.

**Review by joergfunger — APPROVED** [review]

**Pull request merged**
